--
-- PostgreSQL database dump
--

\restrict WC8a4zqF69FSBglNkSrlxykNwwW20svORBgb108PvWfftJL5iXJUpkjWwA1EWhk

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: job_part_jointable; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.job_part_jointable (
    id integer NOT NULL,
    quantity integer,
    job_id integer,
    part_id integer
);


ALTER TABLE public.job_part_jointable OWNER TO app;

--
-- Name: job_part_jointable_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.job_part_jointable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_part_jointable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_status; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.job_status (
    id smallint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.job_status OWNER TO app;

--
-- Name: jobs; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    customer_name character varying(255),
    customer_phone character varying(255),
    job_description character varying(255),
    work_time_minutes integer DEFAULT 0 NOT NULL,
    price_per_minute double precision DEFAULT 0.0 NOT NULL,
    date timestamp without time zone NOT NULL,
    status_id smallint NOT NULL,
    status smallint,
    CONSTRAINT jobs_status_check CHECK (((status >= 0) AND (status <= 5)))
);


ALTER TABLE public.jobs OWNER TO app;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

CREATE SEQUENCE public.jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO app;

--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: app
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: parts; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.parts (
    id integer NOT NULL,
    price double precision,
    title character varying(255),
    type character varying(255)
);


ALTER TABLE public.parts OWNER TO app;

--
-- Name: parts_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO app;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO app;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: app
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: job_part_jointable; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.job_part_jointable (id, quantity, job_id, part_id) FROM stdin;
\.


--
-- Data for Name: job_status; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.job_status (id, name) FROM stdin;
1	notDelivered
2	delivered
3	inProgress
4	missingPart
5	finished
6	pickedUp
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.jobs (id, title, customer_name, customer_phone, job_description, work_time_minutes, price_per_minute, date, status_id, status) FROM stdin;
8	Speed	Jack Johnson	03238202	Nye bremser og ny kæde	120	1	2025-10-15 16:00:00	2	\N
1	Bike Tune-up	Alice Hansen	+4512345678	Full tune-up including brakes	90	1.5	2025-10-10 07:00:00	1	\N
6	Pickup Service	Frank Olsens	+4512340000	Pick up customer bike	60	1	2025-10-13 11:00:00	6	\N
3	Part Delivery	Carol Nielsen	+457070707	Deliver new parts to workshop	15	0.5	2025-10-14 14:30:00	2	\N
5	Gear Adjustment	Eve Petersen	+4598765432	Adjust derailleur and lubricate chain	45	1.2	2025-10-16 13:00:00	5	\N
4	Brake Replacement	David Sørensen	+4523456789	Replace front and rear brake pads	120	2	2025-10-16 10:00:00	4	\N
2	Wheel Alignment	Bob Jensen	+4511122233	Rear wheel alignment	30	1	2025-10-10 11:00:00	3	\N
7	Test Bike A	John Jackson	12412434		60	1	2025-10-09 12:49:00	1	\N
\.


--
-- Data for Name: parts; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.parts (id, price, title, type) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.users (id, email, display_name, created_at) FROM stdin;
1	alice@example.com	Alice	2025-10-07 22:58:04.040653+00
2	bob@example.com	Bob	2025-10-07 22:58:04.040653+00
\.


--
-- Name: job_part_jointable_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.job_part_jointable_id_seq', 1, false);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.jobs_id_seq', 8, true);


--
-- Name: parts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.parts_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: job_part_jointable job_part_jointable_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT job_part_jointable_pkey PRIMARY KEY (id);


--
-- Name: job_status job_status_name_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_status
    ADD CONSTRAINT job_status_name_key UNIQUE (name);


--
-- Name: job_status job_status_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_status
    ADD CONSTRAINT job_status_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: parts parts_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.parts
    ADD CONSTRAINT parts_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_jobs_date; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_jobs_date ON public.jobs USING btree (date);


--
-- Name: idx_jobs_status_id; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_jobs_status_id ON public.jobs USING btree (status_id);


--
-- Name: job_part_jointable fk5f0hi244pf9u22rf7sronksh9; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT fk5f0hi244pf9u22rf7sronksh9 FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: job_part_jointable fktgeatdu2jtolj3tfu2ebd6ftg; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.job_part_jointable
    ADD CONSTRAINT fktgeatdu2jtolj3tfu2ebd6ftg FOREIGN KEY (part_id) REFERENCES public.parts(id);


--
-- Name: jobs jobs_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.job_status(id);


--
-- PostgreSQL database dump complete
--

\unrestrict WC8a4zqF69FSBglNkSrlxykNwwW20svORBgb108PvWfftJL5iXJUpkjWwA1EWhk

